### PR TITLE
week-9

### PR DESCRIPTION
**Pull request by yuhsuanlii**
Name: 李郁玹

http://100.20.194.8:3000/api/attractions?page=1
http://100.20.194.8:3000/api/attractions?page=0&keyword=藝文館所
http://100.20.194.8:3000/api/attractions?page=0&keyword=北
http://100.20.194.8:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK.

But it's much better to use `GROUP_CONCAT` and `JOIN` to combine tables to get attraction data and images all at once, rather than get images one by one.

Try it and re-request review.

**Comment by yuhsuanlii** [comment]
老師您好：我原本設計資料庫時是把篩選好的圖片用逗號隔開，以文字的方式存放在table同一個欄位中，所以取出時才沒有使用到GROUP_CONCAT 和 JOIN的方法。

**Comment by cwpeng** [comment]
OK. I get your point. But what I care is following code:
```
                imgsql = "SELECT images FROM attraction where id = %s"
                params = record[i][0],
                cur.execute(imgsql,params)
                imgdata = cur.fetchall()
                for imgurl in imgdata:
                    img_arr = "".join(imgurl).split(", ")
                    data_dic["images"] = img_arr
```
Obviously, you can get data including images from attraction table at once, don't need to do it one by one, it's expensive.

**Comment by yuhsuanlii** [comment]
I found the problem and solved it! I deleted the code mentioned above and directly used the split() method to convert the string into a list

**Review by cwpeng — DISMISSED** [review]
OK. Done. :)

**Comment by yuhsuanlii** [comment]
Yeah!!!!!!!!!!

**Comment by yuhsuanlii** [comment]
Sorry for press the wrong button, to make sure pull the right edition, I make new pull request.

**Comment by cwpeng** [comment]
You have to request review again. Merge pull request after review approval.

**Comment by yuhsuanlii** [comment]
OK!!!!

**Review by cwpeng — APPROVED** [review]

**Pull request merged**
