### PR TITLE
week-11 (3)

### PR DESCRIPTION
**Pull request by yuhsuanlii**
李郁玹
http://100.20.194.8:3000/
http://100.20.194.8:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Image slider should keep no margin space with navigator bar in mobile version.
2. Text should align to left or right in navigator bar in mobile version. There should have larger space in the middle.
未命名-2

**Comment by yuhsuanlii** [comment]
Got it ! I have corrected and uploaded to EC2.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by yuhsuanlii** [comment]
Thank you !!!!!!!

**Pull request merged**
